### PR TITLE
Fix node-validator's state becoming stale due to disconnected leaf stream

### LINKED ISSUE #2002: Modify `node-metrics` so that it handles when the `ProcessProduceLeafStreamTask` exits its `process_consume_leaf_stream` method
Currently when the `node-validator` service doesn't die when the source `Leaf` `Stream` fails to connect, or dies.  For now, this should be modified to better handle this loop exit.  Ideally this would attempt to reconnect to the stream.  However, it can be easier to just panic initially until this can be handled better.

### PR DESCRIPTION
**Pull request by Ayiga**
Closes #2002

### This PR:

Addresses an issue that occurs when the source Leaf Stream HotShot Query service becomes unavailable, resulting in the node-validator service ending up in a Stale state with no future updates being delivered.

This is implemented with connection re-attempts to acquire a new Leaf Stream should the previous one complete.  The re-attempts themselves will loop to try and ensure a new Leaf Stream is returned with an exponential backkoff up to a maximum limit of 100 times, at which point it will panic as it seems that the service is not going to be coming back immediately.

### CODE REVIEW

File: node-metrics/src/api/node_validator/v0/mod.rs [hunk 1]
```diff
@@ -540,28 +553,93 @@ impl ProcessProduceLeafStreamTask {
...
 
+    async fn connect_and_process_leaves<R, K>(leaf_stream_retriever: R, leaf_sender: K)
+    where
+        R: LeafStreamRetriever<Item = Leaf<SeqTypes>>,
+        K: Sink<Leaf<SeqTypes>, Error = SendError> + Clone + Send + Sync + Unpin + 'static,
+    {
+        // We want to try and ensure that we are connected to the HotShot Query
+        // Service, and are consuming leaves.
+        // - If we are able to connect, then we can start relaying Leaves into
+        //   the leaf sender.  If we are unable
```
Comment (imabdulbasit) [inline node-metrics/src/api/node_validator/v0/mod.rs:564]:
```suggestion
        //   the leaf sender.
```

File: node-metrics/src/api/node_validator/v0/mod.rs [hunk 2]
```diff
@@ -540,28 +553,93 @@ impl ProcessProduceLeafStreamTask {
...
+                        "attempt {attempt} to connect to leaf stream failed with error {error}"
+                    );
+
+                    // Our retry penalty will be a minimum of 100ms, and a maximum
+                    // of 5 seconds.
+                    // For every failed iteration, we will double our delay, up
+                    // to the maximum of 5 seconds.
+
+                    let retry_penalty = max(
+                        Duration::from_millis(100) * 2u32.pow(attempt),
```
Comment (imabdulbasit) [inline node-metrics/src/api/node_validator/v0/mod.rs:618]: if attempt is large like 99 then wouldn't this result in an overflow?

Comment (imabdulbasit) [reply node-metrics/src/api/node_validator/v0/mod.rs:618]: Also we have `BackoffParams` so maybe we can re use it here

Comment (Ayiga) [reply node-metrics/src/api/node_validator/v0/mod.rs:618]: Hmm... the `BackoffParams` seem to indicate that they are used specifically for catchup.  At least that's what the environment variables indicate.  We could still potentially use the default here though.

Also, yeah, you're right... it would overflow as soon as it hits 30 attempts or so.

Comment (Ayiga) [reply node-metrics/src/api/node_validator/v0/mod.rs:618]: `BackOffParams`'s api seems inconvenient at the moment as well.  It assumes an underlying that is being mutated, and requires `anyhow` to operate.

Comment (Ayiga) [reply node-metrics/src/api/node_validator/v0/mod.rs:618]: Though it does look like we might be able to achieve what `BackOffParams::retry` is doing with `backoff` itself.

Comment (imabdulbasit) [reply node-metrics/src/api/node_validator/v0/mod.rs:618]: ok lets leave BackOffParams

**Review by imabdulbasit — APPROVED** [review]
